#!/usr/bin/python
import matplotlib.pyplot as plt
import numpy as np
import sys
plt.style.use(u"trygveplot")


if len(sys.argv)<2:
    print "--------------------------------------------"
    print "Please specify data file: [datplot data.dat]"
    print "--------------------------------------------"
    sys.exit()
file=str(sys.argv[1])
a = np.loadtxt(file)

print len(sys.argv)
if len(sys.argv) > 2:
    min = int(sys.argv[2])
else:
    min = 1

if len(sys.argv) > 3:
    max = int(sys.argv[3])
else:
    max=a.shape[1]

a=a[:,min:max]

f = open(file,"r")
labels = f.readline()
labels = labels.split()
#label = np.genfromtxt(file,dtype='str')
#print label

a = np.loadtxt(file)
print a.shape
a_normed = a#/ a[0,:]



colormap = plt.cm.nipy_spectral

dy = np.diff(a_normed[:,1+min:1+max],axis=0)

a_normed[np.where(dy==0)]=0
plt.subplot(2,1,2)
plt.gca().set_color_cycle([colormap(i) for i in np.linspace(0, 0.9, max-min)])
plt.plot(range(len(a_normed[:,0])-2),dy[:-1])
plt.legend(labels[2+min:2+max],prop={'size': 6}, ncol=1,loc='center left', bbox_to_anchor=(1, 1))
plt.title(file+" derivative")



plt.subplot(2,1,1)
plt.gca().set_color_cycle([colormap(i) for i in np.linspace(0, 0.9, max-min)])
plt.plot(range(len(a_normed[:,0])-1),a_normed[:-1,1+min:1+max])
#plt.legend(labels[2+min:2+max],prop={'size': 6}, ncol=3)
plt.title(file)
plt.tight_layout()
plt.subplots_adjust(right=0.85)
plt.show()
